name: Daily Python Script Execution
on:
  schedule:
    - cron: '0 16 * * *'  # 매일 UTC 16:00 (한국 시간으로 다음날 01:00)에 실행
  workflow_dispatch:
jobs:
  run-python-script:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.PAT }}
        fetch-depth: 0
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt --ignore-installed 
    - name: Install fonts
      run: sudo apt-get install fonts-nanum*
    - name: Run Python script
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: python main.py  
    - name: Commit and push if changes
      run: |
        git config --local user.email yein4452@gmail.com
        git config --local user.name finddme
        git pull
        git add reports/
        git commit -m "Daily update: $(date +'%Y-%m-%d')" || exit 0
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }}
